### PR TITLE
added RDS support

### LINKED ISSUE #1: Adding new services
Hey, I want to make sure I've got the flow down to add new services (e.g. I want RDS in here).  

Can you double check me?

1) update nodeTypes (index.js line 3) with a new entry.  E.g.:
rds: {
	name: "RDS"
	image: "./img/aws/IMAGE.png"
}

2) update nodeConnections (index.js line 54)
with whatever are valid keys from nodeTypes and define the string for "action" for each type you want to support.

3) add the right image to www/img/aws/IMAGE.png. -- looks like 62x64 is the dimensions?

4) Optionally update getEdgeStyle include a case for your action (up in nodeTypes) and define the edge (e.g. color, etc)

### PR DESCRIPTION
**Pull request by fblecha**
Fixes #1

### CODE REVIEW

**Comment by alexcasalboni** [comment]
@fblecha the diff is huge and it includes much more than just RDS support. I'd recommend reverting all the refactoring and eventually opening a separate PR.

**Comment by fblecha** [comment]
@alexcasalboni it's a result of the way the nodeTypes data structure is embedded at the **top** of the file.  Any change there, changes the format for everything else in the file (which is why the diff is huge).  I'd say the first thing is to break that out into another file and import it.

**Comment by alexcasalboni** [comment]
@fblecha yes splitting that file a good idea as well. But I was more concerned about "compromising" the git history just to change `'` into `"` (AFAIK, any IDE can be configured to avoid it).

**Comment by danilop** [comment]
I am not 100% sure I'd add RDS support here. The idea here is not to replicate the CloudFormation Designer or other more advance tools that cover all AWS services, but to have something small and lean to think and design *serverless* apps. Happy to get other feedbacks here.

**Comment by fblecha** [comment]
@danilop I know RDS isn't "serverless" but for some use cases I like having postgresql as my underlying datastore (e.g. postgis, postgraphql, timezones, etc.) and I like being able to use sql as my query language. The use case I use frequently right now for prototyping is API Gateway -> Lambda -> RDS to serve up a graphql endpoint (via postgraphql).  

I was using this as an easy diagramming tool, primarily to show connections/dataflow (vs something like cloud crafted).  

I'm happy to leave this over in my fork if you want to keep this as purely serverless/cost-per-use diagramming tool.

**Comment by danilop** [comment]
Waiting for some feedback here from other users. I would keep this focused on serverless if possible, but RDS, with Amazon Aurora, can trigger Lambda functions, so the border is blurred :)

**Pull request closed without merging**
